// Try Catch
const numero1 = 20;
const numero2 = 30;

console.log(numero1);
console.log(numero2);

try {
    console.log(numero3);
} catch (error) {
    console.log(error);
}